import StyledJsxRegistry from "./registry";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StyledJsxRegistry>
          <main>{children}</main>
        </StyledJsxRegistry>
      </body>
    </html>
  );
}
